import { useEffect, useRef, useState, type FormEvent } from 'react';

type Shipment = {id:string;carrier:string;trackingNumber:string;status:string;lastEventAt:string|null};
type Order = {id:string;customer:string;email:string;total:number;createdAt:string;status:string;taskId:string|null;shipments:Shipment[]};
type Action = {id:string;orderId:string|null;type:string;status:string;attempts:number;maxAttempts:number;nextAttemptAt:string|null;lastError:string|null;createdAt:string};
type Log = {id:string;orderId:string|null;type:string;message:string;createdAt:string};
type Exception = {id:string;orderId:string|null;kind:string;message:string;status:string;createdAt:string;actionId:string|null};
type Overview = {mode:string;metrics:{orders:number;active:number;delivered:number;exceptions:number;successRate:number};orders:Order[];exceptions:Exception[];actions:Action[];logs:Log[];integrations:{name:string;status:string;description:string}[]};
const labels:Record<string,string> = {awaiting_receipt:'Awaiting receipt',pending:'Pending',in_transit:'In transit',partially_delivered:'Partially delivered',delivered:'Delivered',exception:'Exception',succeeded:'Succeeded',retrying:'Retrying',failed:'Failed',open:'Open',resolved:'Resolved'};
const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const date = (s:string) => new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function Badge({status}:{status:string}){return <span className={`badge ${status}`}>{labels[status] ?? status.replaceAll('_',' ')}</span>}
async function api<T>(path:string,body?:unknown):Promise<T>{const res=await fetch(`/api${path}`,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error ?? 'Request failed');return data;}
const scenarios=[['delivery','Complete a delivery','Update a shipment and its fulfillment task.'],['duplicate','Repeat an event','Verify a duplicate is safely ignored.'],['retry','Recover a timeout','Watch a transient failure retry.'],['permanent_failure','Trigger an exception','Create a failure you can replay.'],['out_of_order','Send an older update','Verify a delivered status never regresses.']] as const;
export default function App(){
 const [data,setData]=useState<Overview|null>(null),[view,setView]=useState('overview'),[error,setError]=useState(''),[fetchError,setFetchError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState<'new'|'import'|null>(null),[selected,setSelected]=useState<string|null>(null),[csv,setCsv]=useState(''),[importResult,setImportResult]=useState<{imported:number;duplicates:number;errors:{row:number;message:string}[]}|null>(null);
 const refreshLock=useRef(false),modalRef=useRef<HTMLDialogElement>(null),drawerRef=useRef<HTMLDialogElement>(null);
 async function refresh(){if(refreshLock.current)return;refreshLock.current=true;setRefreshing(true);try{setData(await api<Overview>('/overview'));setFetchError('');}catch(e){setFetchError((e as Error).message);}finally{refreshLock.current=false;setRefreshing(false);}}
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),4000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(modal)modalRef.current?.showModal();else modalRef.current?.close();},[modal]);
 useEffect(()=>{if(selected){setError('');setNotice('');drawerRef.current?.showModal();}else drawerRef.current?.close();},[selected]);
 async function mutate(path:string,body:unknown,message:string){setBusy(true);setError('');try{const result=await api<{message?:string;accepted?:boolean;reason?:string}>(path,body);setNotice(result.accepted===false?`Event ignored: ${result.reason??'no state change needed'}`:result.message??message);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function createOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const result=await api<{duplicate:boolean}>('/orders',{id:f.get('id'),customer:f.get('customer'),email:f.get('email'),total:Number(f.get('total')),shipments:[{carrier:f.get('carrier'),trackingNumber:f.get('tracking')}]});setNotice(result.duplicate?'Identical order already exists.':'Order created. Fulfillment task queued.');setModal(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function importCsv(e:FormEvent){e.preventDefault();setBusy(true);setError('');setImportResult(null);try{setImportResult(await api('/import',{csv}));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const order=data?.orders.find(o=>o.id===selected);
 async function simulateTracking(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const shipment=order?.shipments.find(s=>s.id===f.get('shipment'));if(!shipment)return;await mutate('/events',{id:crypto.randomUUID(),trackingNumber:shipment.trackingNumber,carrier:shipment.carrier,status:f.get('status'),occurredAt:new Date().toISOString()},'Synthetic tracking update processed.');}
 const orders=data?.orders.filter(o=>(filter==='all'||o.status===filter)&&`${o.id} ${o.customer} ${o.email}`.toLowerCase().includes(query.toLowerCase()))??[];
 const openExceptions=data?.exceptions.filter(e=>e.status==='open')??[];
 const title=view==='overview'?'Fulfillment, in focus.':view==='exceptions'?'Keep every order moving.':view==='activity'?'Every step, accounted for.':'Connected by design.';
 return <div className="shell"><aside className="sidebar"><a className="brand" href="#" onClick={()=>setView('overview')}><span className="brand-mark">p</span>parcel<span className="brand-dot">.</span></a><div className="workspace-label">OPERATIONS WORKSPACE</div><nav aria-label="Main navigation">{[['overview','◫','Overview'],['exceptions','◇','Exceptions'],['activity','≋','Activity'],['integrations','⌘','Integrations']].map(([key,icon,label])=><button key={key} className={`nav-item ${view===key?'active':''}`} onClick={()=>setView(key)}><span>{icon}</span>{label}{key==='exceptions'&&openExceptions.length>0&&<b>{openExceptions.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="simulation-pill"><i/> {data?.mode==='connected'?'CONNECTED DEMO':'SIMULATION'}</div><p>Synthetic orders.<br/>Real workflow logic.</p><small>{data?.mode==='connected'?'Real SaaS actions. Synthetic tracking.':<>No connected accounts.<br/>No external messages sent.</>}</small></div><div className="profile"><span>PO</span><div>Portfolio workspace<small>Local demonstration</small></div></div></aside>
 <main><header className="topbar"><span>Workspace <span className="crumb">/</span> {view[0].toUpperCase()+view.slice(1)}</span><div className="topbar-right"><span className="live-dot"/> Local simulation <button className="icon-button" onClick={()=>void refresh()} disabled={refreshing} aria-label="Refresh data">↻</button></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">ORDER OPERATIONS</div><h1>{title}</h1><p>One clear view of orders, deliveries, and the work in between.</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>{setError('');setImportResult(null);setModal('import')}}>↑ Import CSV</button><button className="button primary" onClick={()=>{setError('');setModal('new')}}>＋ New order</button></div></div>
 {(error||fetchError)&&<div className="alert error" role="alert">{error||fetchError}<button aria-label="Dismiss error" onClick={()=>{setError('');setFetchError('')}}>×</button></div>}{notice&&<div className="alert success" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {!data?<section className="card empty"><h2>{fetchError?'API connection unavailable':'Loading your workspace…'}</h2><p>{fetchError?'Start the local API, then refresh to load orders.':'Reading persisted orders and execution records.'}</p><button className="button secondary" onClick={()=>void refresh()}>Refresh</button></section>:<>
 {view==='overview'&&<><div className="metrics">{[['Total orders',data.metrics.orders,'Across this workspace','◫'],['In progress',data.metrics.active,'Awaiting fulfillment','→'],['Delivered',data.metrics.delivered,'All packages delivered','✓'],['Open exceptions',data.metrics.exceptions,'Need a closer look','◇']].map(([label,value,description,icon])=><div className="metric card" key={label}><div className="metric-top">{label}<span>{icon}</span></div><strong>{value}</strong><small>{description}</small></div>)}</div>
 <section className="card orders-card"><div className="section-header"><div><h2>Orders</h2><p>Your fulfillment pipeline, from intake to doorstep.</p></div><span className="muted">{data.orders.length} orders</span></div><div className="table-toolbar"><label className="search"><span>⌕</span><input aria-label="Search orders" placeholder="Search orders or customers…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter order status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{['pending','in_transit','partially_delivered','delivered','exception'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Order / customer</th><th>Status</th><th>Packages</th><th>Order value</th><th>Created</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><button className="order-link" onClick={()=>setSelected(o.id)}>{o.id}</button><span className="customer">{o.customer}</span></td><td><Badge status={o.status}/></td><td><span className="package-count">{o.shipments.filter(s=>s.status==='delivered').length} / {o.shipments.length}</span><span className="mini-progress"><i style={{width:`${o.shipments.filter(s=>s.status==='delivered').length/o.shipments.length*100}%`}}/></span></td><td className="amount">{money(o.total)}</td><td className="muted nowrap">{date(o.createdAt)}</td><td><button className="icon-button" onClick={()=>setSelected(o.id)} aria-label={`View ${o.id}`}>↗</button></td></tr>)}</tbody></table>{orders.length===0&&<div className="empty"><h3>{data.orders.length?'No matching orders':'A clean slate.'}</h3><p>{data.orders.length?'Try another search or status.':'Load synthetic sample orders to explore the workflow.'}</p>{!data.orders.length&&<button disabled={busy} className="button primary" onClick={()=>void mutate('/demo/seed',{},'Sample orders loaded.')}>Load demo orders</button>}</div>}</div><div className="table-footer"><span><i className="live-dot"/> Automatically refreshes every 4 seconds</span><span>Persisted locally in SQLite</span></div></section>
 <div className="lower-grid"><section className="card"><div className="section-header"><div><h2>Workflow playground</h2><p>Test the paths a dependable system handles.</p></div><span className="outline-pill">SIMULATED</span></div><div className="scenario-list">{scenarios.map(([key,label,description],i)=><button disabled={busy||(data.mode==='connected'&&(key==='retry'||key==='permanent_failure'))} className="scenario" key={key} onClick={()=>void mutate('/demo/scenario',{scenario:key},'Scenario completed.')}><span className="scenario-num">0{i+1}</span><span><strong>{label}</strong><small>{description}</small></span><span className="scenario-arrow">↗</span></button>)}</div></section><section className="card"><div className="section-header"><div><h2>Latest activity</h2><p>A trace of what happened and why.</p></div><button className="text-button" onClick={()=>setView('activity')}>View all ↗</button></div><LogList logs={data.logs.slice(0,5)}/><div className="card-bottom"><button disabled={busy} className="button secondary" onClick={()=>void mutate('/digest',{},'Operations summary queued.')}>Generate daily digest</button></div></section></div></>}
 {view==='exceptions'&&<section className="card"><div className="section-header"><div><h2>Exception queue</h2><p>Investigate failures and follow recovery. Demo replay removes the injected failure before retrying.</p></div><span className="outline-pill">{openExceptions.length} OPEN</span></div>{data.exceptions.length===0?<div className="empty"><h3>All clear.</h3><p>No exceptions have been recorded. Try a failure scenario in Overview.</p></div>:<div className="exception-list">{data.exceptions.map(e=><article className="exception" key={e.id}><span className="exception-icon">!</span><div><div className="exception-heading"><strong>{e.kind.replaceAll('_',' ')}</strong><Badge status={e.status}/></div><p>{e.message}</p><small>{e.orderId??'Workspace'} · {date(e.createdAt)}</small></div>{e.actionId&&data.actions.find(a=>a.id===e.actionId)?.status==='failed'&&<button disabled={busy} className="button secondary" onClick={()=>void mutate(`/actions/${e.actionId}/replay`,{},'Action replay queued.')}>{data.mode==='connected'?'Replay corrected action':'Repair & replay (demo)'} ↻</button>}</article>)}</div>}</section>}
 {view==='activity'&&<><section className="card"><div className="section-header"><div><h2>Execution queue</h2><p>Attempts, retries, and final outcomes are persisted.</p></div><button disabled={busy} className="button secondary" onClick={()=>void mutate('/actions/process',{},'Eligible queue actions processed.')}>Process eligible actions</button></div><div className="table-scroll"><table><thead><tr><th>Action</th><th>Order</th><th>Status</th><th>Attempts</th><th>Details</th></tr></thead><tbody>{data.actions.map(a=><tr key={a.id}><td><strong>{a.type.replaceAll('_',' ')}</strong><small className="block mono">{a.id}</small></td><td>{a.orderId??'Workspace'}</td><td><Badge status={a.status}/></td><td>{a.attempts}/{a.maxAttempts}</td><td className="action-detail">{a.lastError??'—'}{a.nextAttemptAt&&<small className="block">Next attempt {date(a.nextAttemptAt)}</small>}{a.status==='failed'&&<button disabled={busy} className="text-button" onClick={()=>void mutate(`/actions/${a.id}/replay`,{},'Action replay queued.')}>{data.mode==='connected'?'Replay corrected action':'Repair & replay (demo)'} ↻</button>}</td></tr>)}</tbody></table>{!data.actions.length&&<div className="empty">No actions yet.</div>}</div></section><section className="card activity-card"><div className="section-header"><div><h2>Event timeline</h2><p>Intake, status changes, and reliability decisions.</p></div></div><LogList logs={data.logs}/></section></>}
 {view==='integrations'&&<><div className="simulation-note"><span>◇</span><div><strong>{data.mode==='connected'?'Connected demo — synthetic logistics':'This workspace runs entirely in simulation.'}</strong><p>{data.mode==='connected'?'SaaS actions require verified execution receipts. Configuration alone does not prove an action succeeded.':'Provider actions are written to a local outbox. No accounts are connected and no notifications leave this application.'}</p></div></div><div className="integration-grid">{data.integrations.map((i,index)=><section className="card integration-card" key={i.name}><div className="integration-top"><span className={`integration-icon provider-${index}`}>{i.name.slice(0,1)}</span><span className="outline-pill">{i.status.toUpperCase()}</span></div><h2>{i.name}</h2><p>{i.description}</p><div className="integration-footer"><span className="live-dot"/> {i.status==='simulated'?'Local provider simulation':'Execution receipts tracked in Activity'}</div></section>)}</div><section className="card reliability"><h2>Built for the imperfect path.</h2><p>Duplicate events are ignored. Older updates cannot regress delivered shipments. Failed actions retry with a capped delay, then surface in the exception queue for review.</p><span>Live integrations require provider credentials and separate end-to-end validation.</span></section></>}
 </>}
 <footer className="footer"><span>PARCEL / ORDER OPERATIONS DEMO</span><span>{data?.mode==='connected'?'Synthetic logistics · Real SaaS actions · Receipts required':'Synthetic data · Local execution · No live integrations'}</span></footer></div></main>
 <dialog ref={modalRef} aria-label={modal==='new'?'Create an order':'Import orders'} className="modal" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal-heading"><div><div className="eyebrow">ORDER INTAKE</div><h2>{modal==='new'?'Create an order':'Import orders'}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}>×</button></div>{error&&<div className="alert error" role="alert">{error}</div>}{modal==='new'?<form onSubmit={createOrder}><p className="muted">Use synthetic data only. Check Integrations for the current execution mode.</p><div className="form-grid"><label>Order ID<input name="id" required placeholder="ORD-1042"/></label><label>Customer<input name="customer" required placeholder="Alex Morgan"/></label><label>Email<input name="email" type="email" required placeholder="alex@example.com"/></label><label>Total (USD)<input name="total" type="number" step="0.01" min="0" required placeholder="129.00"/></label><label>Carrier<input name="carrier" required placeholder="UPS"/></label><label>Tracking number<input name="tracking" required placeholder="DEMO-1042"/></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancel</button><button disabled={busy} className="button primary" type="submit">{busy?'Creating…':'Create order'}</button></div></form>:<form onSubmit={importCsv}><p className="muted">One row per package. Rows sharing an order ID are grouped. Invalid orders are skipped with an explanation.</p><label className="file-label">Choose a CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f)setCsv(await f.text())}}/></label><label className="csv-label">CSV content<textarea rows={8} required value={csv} onChange={e=>setCsv(e.target.value)} placeholder={'order_id,customer,email,total,carrier,tracking_number\nORD-1042,Alex Morgan,alex@example.com,129,UPS,DEMO-1042'}/></label>{importResult&&<div className="import-result" role="status"><strong>{importResult.imported} imported · {importResult.duplicates} duplicates</strong>{importResult.errors.map((e,i)=><p key={i}>Row {e.row}: {e.message}</p>)}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Close</button><button type="submit" disabled={busy} className="button primary">{busy?'Importing…':'Import orders'}</button></div></form>}</dialog>
 <dialog ref={drawerRef} aria-label="Order details" className="drawer" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}>{order&&<><div className="modal-heading"><div><div className="eyebrow">ORDER DETAILS</div><h2>{order.id}</h2></div><button className="icon-button" aria-label="Close order details" onClick={()=>setSelected(null)}>×</button></div>{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}<Badge status={order.status}/><div className="detail-summary"><div><small>Customer</small><strong>{order.customer}</strong><span>{order.email}</span></div><div><small>Order value</small><strong>{money(order.total)}</strong><span>{date(order.createdAt)}</span></div></div><div className="detail-task"><span>Fulfillment task</span><code>{order.taskId??'Queued — awaiting creation'}</code></div><h3>Packages <span className="muted">({order.shipments.length})</span></h3>{order.shipments.map(s=><div className="shipment" key={s.id}><div><strong>{s.carrier}</strong><Badge status={s.status}/></div><code>{s.trackingNumber}</code><small>{s.lastEventAt?`Last update ${date(s.lastEventAt)}`:'No tracking updates received'}</small></div>)}<form className="tracking-simulator" key={order.id} onSubmit={simulateTracking}><div className="simulator-heading"><strong>Simulate tracking update</strong><span className="outline-pill">SYNTHETIC EVENT</span></div><p>Send a synthetic tracking event. No carrier is contacted; connected mode may update demo tasks and send alerts.</p><label>Package<select name="shipment" required>{order.shipments.map(s=><option key={s.id} value={s.id}>{s.carrier} · {s.trackingNumber}</option>)}</select></label><label>Tracking status<select name="status" defaultValue="in_transit"><option value="in_transit">In transit</option><option value="delivered">Delivered</option><option value="exception">Exception</option></select></label><button type="submit" className="button secondary" disabled={busy}>{busy?'Processing…':'Send synthetic update'}</button></form><h3>Order activity</h3><LogList logs={data?.logs.filter(l=>l.orderId===order.id)??[]}/></>}</dialog>
 </div>;
}
function LogList({logs}:{logs:Log[]}){return <div className="log-list">{logs.length?logs.map(l=><div className="log-item" key={l.id}><span className="log-dot"/><div><strong>{l.message}</strong><small>{l.orderId?`${l.orderId} · `:''}{l.type.replaceAll('_',' ')} · {date(l.createdAt)}</small></div></div>):<div className="empty compact">No activity recorded yet.</div>}</div>}
