import {writeFileSync,mkdirSync} from 'node:fs';
import {Engine} from '../../server/engine';
import {scenes,duration} from '../src/timeline';
let now=new Date('2026-10-08T11:00:00.000Z');
const engine=new Engine(':memory:',()=>now,'simulation');
const snapshots:Record<string,ReturnType<Engine['overview']>>={};
const csv='order_id,customer,email,total,carrier,tracking_number\nPORTFOLIO-2001,Cedar Workflow Studio,demo@example.com,148,UPS,DEMO-PORTFOLIO-A\nPORTFOLIO-2001,Cedar Workflow Studio,demo@example.com,148,USPS,DEMO-PORTFOLIO-B';
const save=(name:string)=>{snapshots[name]=engine.overview();};
engine.seed();engine.process();save('overview');
const imported=engine.importCsv(csv);if(imported.imported!==1||imported.errors.length)throw Error('Intake replay failed');
engine.process();save('pending');
const event={id:'VIDEO-DELIVERY-A',carrier:'UPS',trackingNumber:'DEMO-PORTFOLIO-A',status:'delivered',occurredAt:'2026-10-08T11:01:00.000Z'};
now=new Date(event.occurredAt);engine.applyEvent(event);engine.process();save('partial');
now=new Date('2026-10-08T11:02:00.000Z');engine.applyEvent({...event,id:'VIDEO-DELIVERY-B',carrier:'USPS',trackingNumber:'DEMO-PORTFOLIO-B',occurredAt:now.toISOString()});engine.process();save('complete');
const before=engine.all('actions').length;
const duplicate=engine.applyEvent(event);
const stale=engine.applyEvent({...event,id:'VIDEO-STALE',status:'in_transit',occurredAt:'2026-10-08T10:59:00.000Z'});
if(duplicate.accepted||stale.accepted||before!==engine.all('actions').length)throw Error('Reliability replay failed');
save('reliability');engine.close();
if(snapshots.partial.orders.find(o=>o.id==='PORTFOLIO-2001')?.status!=='partially_delivered'||snapshots.complete.orders.find(o=>o.id==='PORTFOLIO-2001')?.status!=='delivered')throw Error('Package aggregation replay failed');
if(duration!==3600)throw Error('Timeline must remain two minutes; update encoding metadata if changing duration');
const ids=new Map<string,string>();const raw=JSON.stringify({csv,snapshots,scenes,duration});
const normalized=raw.replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/g,id=>{if(!ids.has(id))ids.set(id,`REPLAY-${String(ids.size+1).padStart(3,'0')}`);return ids.get(id)!;});
mkdirSync('media/public/generated',{recursive:true});writeFileSync('media/public/generated/replay.json',normalized+'\n');
console.log('Replay passed: intake, partial/full aggregation, duplicate/stale rejection, unchanged action count.');
