import { describe,it,expect,afterEach } from 'vitest';
import { Engine,demoOrders,type Action,type Order } from '../server/engine.js';
import { ZapierBridge } from '../server/bridge.js';
import { makeApp } from '../server/app.js';
const engines:Engine[]=[];afterEach(()=>{for(const e of engines)e.close();engines.length=0;});
const token='test-receipt-token-with-at-least-32-characters';
const hook='https://hooks.zapier.com/hooks/catch/test/test/';
function setup(transport:ConstructorParameters<typeof ZapierBridge>[2]=async()=>({ok:true,status:200})){
 let time=Date.parse('2026-10-08T08:00:00Z');const e=new Engine(':memory:',()=>new Date(time),'connected');engines.push(e);
 const bridge=new ZapierBridge(e,{hooks:{create_task:hook,update_task:hook,notify:hook,daily_digest:hook},callbackBaseUrl:'https://demo.example.com/',receiptToken:token,receiptTimeoutMs:1000},transport);
 const action=e.addOrder(demoOrders[0]);return {e,bridge,advance:()=>time+=2000,order:action.order,first:()=>e.all<Action>('actions').reverse()[0]};
}
describe('connected outbox',()=>{
 it('does not interpret an HTTP 200 webhook response as successful provider execution',async()=>{const {e,bridge,first}=setup();expect(e.process().processed).toBe(0);await bridge.tick();expect(first().status).toBe('awaiting_receipt');expect(e.get<Order>('orders',demoOrders[0].id)!.taskId).toBeNull();});
 it('requires a real task ID, accepts duplicate receipts idempotently and rejects conflicts',async()=>{const {e,bridge,first}=setup();await bridge.tick();const receipt={action_id:first().id,attempt:1,outcome:'succeeded'};expect(()=>bridge.receipt(receipt)).toThrow('real task ID');bridge.receipt({...receipt,task_id:'real-task-123'});expect(e.get<Order>('orders',demoOrders[0].id)!.taskId).toBe('real-task-123');expect(bridge.receipt({...receipt,task_id:'real-task-123'}).accepted).toBe(false);expect(()=>bridge.receipt({...receipt,task_id:'different'})).toThrow('Conflicting');});
 it('pauses ambiguous outcomes without resending and reconciles a late success receipt',async()=>{let calls=0;const {bridge,first,e,advance}=setup(async()=>{calls++;throw new Error('credential-containing transport error');});await bridge.tick();expect(first().status).toBe('failed');expect(first().lastError).not.toContain('credential');expect(()=>e.replay(first().id)).toThrow('uncertain');advance();await bridge.tick();expect(calls).toBe(1);bridge.receipt({action_id:first().id,attempt:1,outcome:'succeeded',task_id:'real-task-123'});expect(first().status).toBe('succeeded');expect(e.overview().metrics.exceptions).toBe(0);});
 it('retries an explicit ingress rate limit and rejects stale-attempt receipts',async()=>{let calls=0;const {bridge,first,advance}=setup(async()=>({ok:++calls>1,status:calls===1?429:200}));await bridge.tick();expect(first().status).toBe('retrying');advance();await bridge.tick();expect(first().attempts).toBe(2);expect(()=>bridge.receipt({action_id:first().id,attempt:1,outcome:'succeeded',task_id:'old'})).toThrow('attempt');});
 it('expires a missing receipt and leaves the ambiguous action for reconciliation',async()=>{const {bridge,first,advance}=setup();await bridge.tick();advance();await bridge.tick();expect(first().status).toBe('failed');expect(first().uncertain).toBe(true);});
 it('serializes order actions and dispatches updates only after the creation receipt',async()=>{const payloads:any[]=[];const {bridge,e,first}=setup(async(_url,init)=>{payloads.push(JSON.parse(String(init.body)));return {ok:true,status:200};});e.applyEvent({id:'delivery',carrier:'UPS',trackingNumber:'DEMO-UPS-1042-A',status:'delivered',occurredAt:e.now()});await bridge.tick();expect(payloads).toHaveLength(1);bridge.receipt({action_id:first().id,attempt:1,outcome:'succeeded',task_id:'real-task'});await bridge.tick();expect(payloads).toHaveLength(2);expect(payloads[1].task_id).toBe('real-task');expect(payloads[1].status).toBe('partially_delivered');expect(payloads[1].clickup_status).toBe('to do');});
 it('guards against overlapping workers',async()=>{let release!:()=>void;const {bridge}=setup(async()=>{await new Promise<void>(r=>release=r);return {ok:true,status:200};});const running=bridge.tick();expect((await bridge.tick()).processed).toBe(0);release();await running;});
 it('recovers the in-flight deadline when the worker is replaced',async()=>{const {bridge,e,first,advance}=setup();await bridge.tick();const saved=first();expect(saved.receiptDeadline).toBeTruthy();const newBridge=new ZapierBridge(e,bridge.config);advance();await newBridge.tick();expect(first().uncertain).toBe(true);});
 it('rejects foreign endpoints before any data can leave the application',()=>{const {e}=setup();expect(()=>new ZapierBridge(e,{hooks:{create_task:'https://evil.example/'},callbackBaseUrl:'https://demo.example/',receiptToken:token})).toThrow('Zapier');});
});
describe('deployment access protection',()=>{
 it('requires callback authorization, hides operational data and denies cross-site writes',async()=>{const {bridge,e,first}=setup();const app=makeApp(e,{bridge,accessPassword:'long-demo-password',receiptToken:token});expect((await app.inject('/health')).statusCode).toBe(200);expect((await app.inject('/api/overview')).statusCode).toBe(401);const auth='Basic '+Buffer.from('demo:long-demo-password').toString('base64');expect((await app.inject({url:'/api/overview',headers:{authorization:auth}})).statusCode).toBe(200);expect((await app.inject({method:'POST',url:'/api/digest',headers:{authorization:auth,origin:'https://evil.example'},payload:{}})).statusCode).toBe(403);await bridge.tick();const payload={action_id:first().id,attempt:1,outcome:'succeeded',task_id:'real-task'};expect((await app.inject({method:'POST',url:'/api/integrations/receipt',payload})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/integrations/receipt',headers:{authorization:'Bearer '+token},payload})).statusCode).toBe(200);await app.close();});
});
